# Generated by Django 5.2.4 on 2025-08-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="messaging.message",
            ),
        ),
    ]
